import type { Metadata } from "next";
import "./globals.css";

import Theme from "@/context/theme-context";

import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="bg-gray-200 text-gray-900 dark:bg-gray-950 dark:text-gray-50"
        suppressHydrationWarning
      >
        <Theme>
          <Navbar />

          <main className="px-5 ml-16">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
